services:
  curas-server:
    image: cr.blac.dev/curas/server:latest
    container_name: curas 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    ports:
      - "8080:8080"
