services:
  curas-server:
    image: cr.blac.dev/curas/server:latest
    container_name: curas 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env
    ports:
      - "8080:8080"
  redis:
    image: redis:8.2.2
    command:
      - redis-server
      - --save ""
      - --appendonly no
      - --maxmemory 512mb
      - --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    restart: unless-stopped
