name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.java'
      - 'build.gradle'
      - 'build.gradle.kts'
      - 'settings.gradle*'
      - 'gradle/**'

jobs:
  spotless:
    name: Spotless
    runs-on: self-hosted

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify formatting
        run: ./gradlew --no-daemon spotlessCheck
