# name: Format
#
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "**/*.java"
#       - "**/*.kt"
#       - "build.gradle"
#       - "build.gradle.kts"
#       - "gradle/**"
#       - "settings.gradle*"
#   workflow_dispatch:
#
# permissions:
#   contents: write # required to push commits
#
# concurrency:
#   group: spotless-${{ github.ref }}
#   cancel-in-progress: true
#
# jobs:
#   format:
#     runs-on: self-hosted
#
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 # needed so we can push back
#
#       - name: Set up Java
#         uses: actions/setup-java@v4
#         with:
#           distribution: oracle 
#           java-version: "25"
#           cache: gradle
#
#       - name: Setup Gradle
#         uses: gradle/actions/setup-gradle@v4
#
#       - name: Spotless apply
#         run: ./gradlew --no-daemon spotlessApply
#
#       - name: Commit changes (if any)
#         uses: stefanzweifel/git-auto-commit-action@v5
#         with:
#           commit_message: "chore(format): spotlessApply [skip ci]"
#           file_pattern: |
#             **/*.java
#             **/*.kt
